# Generated by Django 5.2.4 on 2025-08-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.province')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.country')),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.region'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=20)),
                ('paternal_lastname', models.CharField(max_length=100)),
                ('maternal_lastname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('personal_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ocupation', models.CharField(blank=True, max_length=100, null=True)),
                ('health_condition', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.district')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.documenttype')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.province')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.region')),
            ],
        ),
    ]
