# Generated by Django 5.2.4 on 2025-08-20 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reflexo', '0001_initial'),
        ('patients_diagnoses', '0002_alter_patient_country_remove_region_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_patients', to='Reflexo.country'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_patients', to='Reflexo.district'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_patients', to='Reflexo.province'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_patients', to='Reflexo.region'),
        ),
    ]
